services:
  #    ava@pop-os:~$ docker run --rm -it -p 5000:80 -p 2525:25 rnwood/smtp4dev
  mailserver:
    image: rnwood/smtp4dev
    container_name: mail-server
    ports:
      - "5000:80"
      - "2525:25"
  postgres:
    image: postgres
    container_name: "postgres-1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - DB:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: greybeast@popos.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"
volumes:
  DB:
