spring:
  application:
    name: ecommerce-backend
  mail:
    host: localhost
    port: 2525
  datasource:
    username: postgres
    password: password
    url: "jdbc:postgresql://localhost:5432/ecommerce"
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api/v1

management:
  endpoints:
    jmx:
      exposure:
        include: "*"

encryption:
  salt:
    rounds: 10

jwt:
  algorithm:
    key: "greybeast declares this secure"
  issuer: "greybeast"
  expiryInSeconds: 600

app:
  frontend-url: "localhost:8000"

mail-server:
  from: greybeast@spring.com
